### PR TITLE
EFS API: Add support from payment template activation dates

### PR DESCRIPTION
**Pull request by hepsimo**
Support activation dates for form payment templates:
- allow multiple payment templates associated with the same form template,  each with a separate activation date (including future dates)
- for the `submission/{id}/payment` endpoint, enhance lookup of the selected form's payment template by selecting the currently active one
- expose test/diagnostic endpoints with feature flag `$FEATURE_TESTING_FEES`, defaults to `false`
1.  `GET /payment-templates?type=<FEE_ID>&activeAt=<CHARGE_DATE_TIME>`: find the current fees for the form template `FORM_TEMPLATE`: select the associated payment template having the latest activation date that is not after `CHARGE_DATE_TIME`
    - e.g. `GET /payment-templates?fee=SLPCS01&chargedAt=2023-10-01T12:34:56`
1. `/payment-templates?fee=<FEE_ID>`: find all payment templates associated with a form template (including future dates)
    - e.g. `GET /payment-templates?fee=SLPCS01`
1. `GET /payment-templates`: find all payment templates
1. `POST /payment-templates/test-fee`: create and store a payment template for test purposes
    - e.g. `POST /payment-templates/test-fee`
```json
{
  "fee": "SLPCS01",
  "active_from": "2023-10-10T00:00:00",
  "amount": "99"
}
```

Resolves:
FEE-190

### CODE REVIEW

**Review by PhilipGlover — COMMENTED** [review]
I'm trying everything and it all works as expected so far.  The only thing I've seen so far is:

**Review by PhilipGlover — COMMENTED** [review]
What I did:
- made no change to payment collection - have used EFS web for the 4 forms and seen fee as expected on all screens, and in payment service
- then added a new SLPCS01 document into payment collection, dated 1 Oct 2023 for £20 and this new fee showed in EFS screens and payment screens
- made API call to http://api.chs.local/efs-submission-api/payment-templates?type=SLPCS01&activeAt=2023-10-01T12:34:56 and my new document returned as expected
- made API call to http://api.chs.local/efs-submission-api/payment-templates?type=SLPCS01 returned 2 documents
- mvn verify Build Success / Tests run ok
- have switched Feature on and off, and access to /payment-templates ok/not found
- looked over code and all looks good to me, nice work
- happy to approve once my question about the POST to test-fee answered

**Comment by hepsimo** [comment]
@PhilipGlover Good spot. I've corrected the JSON in the description above for the POST:
Wrong property name, should be `active_from` not `activeFrom`
Please retry, you should get the response
```json
{
	"id": {
		"fee": "SLPCS01",
		"active_from": "2023-10-01T00:00:00"
	},
	"items": [
		{
			"amount": "99"
		}
	]
}
```
and corresponding entry in mongodb

**Review by PhilipGlover — APPROVED** [review]
Retested the `payment-templates/test-fee` endpoint with body as advised by Simon, and data stored as expected now.
Great stuff!

**Pull request merged**
