### PR TITLE
Fix sonar issues incl. method complexity

### PR DESCRIPTION
**Pull request by hepsimo**
- refactor complex SubmissionValidator logic into validators using Chain of Responsibility pattern
- add/replace unit tests to maintain test coverage

Resolves:
BI-5561

### CODE REVIEW

**Review by clewis1 — COMMENTED** [review]
Look good to me.
Suggest a second pair of eyes take a look to double check.

**Comment by PhilipGlover** [comment]
tried to complete journey all the way through for a RP02A but got:

**Comment by PhilipGlover** [comment]
2020-11-04T09:07:54.654Z [5fa26f0211dfba5a2c524223] error: Submission invalid
  -> created: 2020-11-04T09:07:54.654Z
  -> event: error
  -> namespace: efs-submission-api
  -> context: 5fa26f0211dfba5a2c524223
  -> submissionId: 5fa26f0211dfba5a2c524223
  -> exceptionMessage: Fee amount is missing for form [RP02A] in submission [5fa26f0211dfba5a2c524223]

**Comment by PhilipGlover** [comment]
No payment RP02A now ok.
But after paying for my SQPCS01, when returning from payment service I get an error. Logs:
`2020-11-04T10:55:46.509Z [/efs-submission-api/submission/5fa28883062dbe1bc4ba1be8] error: SDK exception
  -> created: 2020-11-04T10:55:46.509Z
  -> event: error
  -> namespace: efs-submission-web
  -> context: /efs-submission-api/submission/5fa28883062dbe1bc4ba1be8
  -> operationName: completeSubmission
  -> requestUri: /efs-submission-api/submission/5fa28883062dbe1bc4ba1be8
  -> stack_trace: ApiErrorResponseException [details=ApiErrorResponse [errors=[]], getStatusCode()=400, getStatusMes
sage()=Bad Request, getMessage()=null]
uk.gov.companieshouse.api.error.ApiErrorResponseException.fromHttpResponseException(ApiErrorResponseException.java:2
6)
uk.gov.companieshouse.api.request.impl.RequestExecutorImpl.putRequest(RequestExecutorImpl.java:131)
uk.gov.companieshouse.api.handler.efs.submissions.request.PrivateModelUpsert.execute(PrivateModelUpsert.java:31)
uk.gov.companieshouse.api.handler.efs.submissions.request.PrivateModelUpsert.execute(PrivateModelUpsert.java:13)
uk.gov.compani`

and 

` -> error: ApiErrorResponseException [details=ApiErrorResponse [errors=[]], getStatusCode()=400, getStatusMessage()=Bad Request, getMessage()=null]
2020-11-04T10:55:46.509Z [5fa28883062dbe1bc4ba1be8] info: Submission completed
  -> created: 2020-11-04T10:55:46.509Z
  -> event: info
  -> namespace: efs-submission-web
  -> context: 5fa28883062dbe1bc4ba1be8
  -> companyNumber: 00006400
  -> id: 5fa28883062dbe1bc4ba1be8
2020-11-04T10:55:46.512Z [5fa28883062dbe1bc4ba1be8] error: 400 BAD_REQUEST "Bad Request"; nested exception is ApiErrorResponseException [details=ApiErrorResponse [errors=[]], getStatusCode()=400, getStatusMessage()=Bad Request, getMessage()=null]
  -> created: 2020-11-04T10:55:46.512Z
  -> event: error
  -> namespace: efs-submission-web
  -> context: 5fa28883062dbe1bc4ba1be8
  -> companyNumber: 00006400
  -> id: 5fa28883062dbe1bc4ba1be8
  -> stack_trace: org.springframework.web.server.ResponseStatusException: 400 BAD_REQUEST "Bad Request"; nested exception is ApiErrorResponseException [details=ApiErrorResponse [errors=[]], getStatusCode()=400, getStatusMessage()=Bad Request, getMessage()=null]
uk.gov.companieshouse.efs.web.service.api.impl.BaseApiClientServiceImpl.executeOp(BaseApiClientServiceImpl.java:53)
uk.gov`

**Comment by hepsimo** [comment]
Good spot. It's a bug in FesAttachmentValidator. I'm working on a fix.

**Review by PhilipGlover — APPROVED** [review]
web journeys for several forms ok, fee bearing and not.
Successful payment and cancelled.
I then completed a submission, then in db removed the presenter.  When I `PUT` from postman to update the status, it correctly errored and logged `Presenter details are absent in submission`

All looks good to me.. nice refactor.

**Pull request merged**
